//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePrototypeClient.GamePrototypeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GamePrototypeServiceReference.IGamePrototypeService")]
    public interface IGamePrototypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetUserByLogin", ReplyAction="http://tempuri.org/IGamePrototypeService/GetUserByLoginResponse")]
        GamePrototypeClasses.user.UserProfile GetUserByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetUserByLogin", ReplyAction="http://tempuri.org/IGamePrototypeService/GetUserByLoginResponse")]
        System.Threading.Tasks.Task<GamePrototypeClasses.user.UserProfile> GetUserByLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetUserByEmail", ReplyAction="http://tempuri.org/IGamePrototypeService/GetUserByEmailResponse")]
        GamePrototypeClasses.user.UserProfile GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetUserByEmail", ReplyAction="http://tempuri.org/IGamePrototypeService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<GamePrototypeClasses.user.UserProfile> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/IsUserLoginDataValid", ReplyAction="http://tempuri.org/IGamePrototypeService/IsUserLoginDataValidResponse")]
        bool IsUserLoginDataValid(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/IsUserLoginDataValid", ReplyAction="http://tempuri.org/IGamePrototypeService/IsUserLoginDataValidResponse")]
        System.Threading.Tasks.Task<bool> IsUserLoginDataValidAsync(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetAllThings", ReplyAction="http://tempuri.org/IGamePrototypeService/GetAllThingsResponse")]
        GamePrototypeClasses.game.thinks.Things[] GetAllThings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetAllThings", ReplyAction="http://tempuri.org/IGamePrototypeService/GetAllThingsResponse")]
        System.Threading.Tasks.Task<GamePrototypeClasses.game.thinks.Things[]> GetAllThingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetAllCharacterThings", ReplyAction="http://tempuri.org/IGamePrototypeService/GetAllCharacterThingsResponse")]
        GamePrototypeClasses.game.character.warehouse.CharacterThings[] GetAllCharacterThings(GamePrototypeClasses.game.character.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetAllCharacterThings", ReplyAction="http://tempuri.org/IGamePrototypeService/GetAllCharacterThingsResponse")]
        System.Threading.Tasks.Task<GamePrototypeClasses.game.character.warehouse.CharacterThings[]> GetAllCharacterThingsAsync(GamePrototypeClasses.game.character.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetCharacterById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetCharacterByIdResponse")]
        GamePrototypeClasses.game.character.Character GetCharacterById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetCharacterById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetCharacterByIdResponse")]
        System.Threading.Tasks.Task<GamePrototypeClasses.game.character.Character> GetCharacterByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetWarehouseById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetWarehouseByIdResponse")]
        GamePrototypeClasses.game.character.warehouse.CharacterWarehouse GetWarehouseById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetWarehouseById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetWarehouseByIdResponse")]
        System.Threading.Tasks.Task<GamePrototypeClasses.game.character.warehouse.CharacterWarehouse> GetWarehouseByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetUserProfile", ReplyAction="http://tempuri.org/IGamePrototypeService/SetUserProfileResponse")]
        void SetUserProfile(GamePrototypeClasses.user.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetUserProfile", ReplyAction="http://tempuri.org/IGamePrototypeService/SetUserProfileResponse")]
        System.Threading.Tasks.Task SetUserProfileAsync(GamePrototypeClasses.user.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/SetCharacterResponse")]
        void SetCharacter(GamePrototypeClasses.game.character.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/SetCharacterResponse")]
        System.Threading.Tasks.Task SetCharacterAsync(GamePrototypeClasses.game.character.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/UpdateCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/UpdateCharacterResponse")]
        void UpdateCharacter(GamePrototypeClasses.game.character.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/UpdateCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/UpdateCharacterResponse")]
        System.Threading.Tasks.Task UpdateCharacterAsync(GamePrototypeClasses.game.character.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetThing", ReplyAction="http://tempuri.org/IGamePrototypeService/SetThingResponse")]
        void SetThing(GamePrototypeClasses.game.thinks.Things thing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetThing", ReplyAction="http://tempuri.org/IGamePrototypeService/SetThingResponse")]
        System.Threading.Tasks.Task SetThingAsync(GamePrototypeClasses.game.thinks.Things thing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetThingToCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/SetThingToCharacterResponse")]
        void SetThingToCharacter(GamePrototypeClasses.game.thinks.Things thing, GamePrototypeClasses.game.character.warehouse.CharacterWarehouse warehouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetThingToCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/SetThingToCharacterResponse")]
        System.Threading.Tasks.Task SetThingToCharacterAsync(GamePrototypeClasses.game.thinks.Things thing, GamePrototypeClasses.game.character.warehouse.CharacterWarehouse warehouse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGamePrototypeServiceChannel : GamePrototypeClient.GamePrototypeServiceReference.IGamePrototypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GamePrototypeServiceClient : System.ServiceModel.ClientBase<GamePrototypeClient.GamePrototypeServiceReference.IGamePrototypeService>, GamePrototypeClient.GamePrototypeServiceReference.IGamePrototypeService {
        
        public GamePrototypeServiceClient() {
        }
        
        public GamePrototypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GamePrototypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamePrototypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamePrototypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GamePrototypeClasses.user.UserProfile GetUserByLogin(string login) {
            return base.Channel.GetUserByLogin(login);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClasses.user.UserProfile> GetUserByLoginAsync(string login) {
            return base.Channel.GetUserByLoginAsync(login);
        }
        
        public GamePrototypeClasses.user.UserProfile GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClasses.user.UserProfile> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public bool IsUserLoginDataValid(string login, string pass) {
            return base.Channel.IsUserLoginDataValid(login, pass);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserLoginDataValidAsync(string login, string pass) {
            return base.Channel.IsUserLoginDataValidAsync(login, pass);
        }
        
        public GamePrototypeClasses.game.thinks.Things[] GetAllThings() {
            return base.Channel.GetAllThings();
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClasses.game.thinks.Things[]> GetAllThingsAsync() {
            return base.Channel.GetAllThingsAsync();
        }
        
        public GamePrototypeClasses.game.character.warehouse.CharacterThings[] GetAllCharacterThings(GamePrototypeClasses.game.character.Character character) {
            return base.Channel.GetAllCharacterThings(character);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClasses.game.character.warehouse.CharacterThings[]> GetAllCharacterThingsAsync(GamePrototypeClasses.game.character.Character character) {
            return base.Channel.GetAllCharacterThingsAsync(character);
        }
        
        public GamePrototypeClasses.game.character.Character GetCharacterById(System.Guid id) {
            return base.Channel.GetCharacterById(id);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClasses.game.character.Character> GetCharacterByIdAsync(System.Guid id) {
            return base.Channel.GetCharacterByIdAsync(id);
        }
        
        public GamePrototypeClasses.game.character.warehouse.CharacterWarehouse GetWarehouseById(System.Guid id) {
            return base.Channel.GetWarehouseById(id);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClasses.game.character.warehouse.CharacterWarehouse> GetWarehouseByIdAsync(System.Guid id) {
            return base.Channel.GetWarehouseByIdAsync(id);
        }
        
        public void SetUserProfile(GamePrototypeClasses.user.UserProfile userProfile) {
            base.Channel.SetUserProfile(userProfile);
        }
        
        public System.Threading.Tasks.Task SetUserProfileAsync(GamePrototypeClasses.user.UserProfile userProfile) {
            return base.Channel.SetUserProfileAsync(userProfile);
        }
        
        public void SetCharacter(GamePrototypeClasses.game.character.Character character) {
            base.Channel.SetCharacter(character);
        }
        
        public System.Threading.Tasks.Task SetCharacterAsync(GamePrototypeClasses.game.character.Character character) {
            return base.Channel.SetCharacterAsync(character);
        }
        
        public void UpdateCharacter(GamePrototypeClasses.game.character.Character character) {
            base.Channel.UpdateCharacter(character);
        }
        
        public System.Threading.Tasks.Task UpdateCharacterAsync(GamePrototypeClasses.game.character.Character character) {
            return base.Channel.UpdateCharacterAsync(character);
        }
        
        public void SetThing(GamePrototypeClasses.game.thinks.Things thing) {
            base.Channel.SetThing(thing);
        }
        
        public System.Threading.Tasks.Task SetThingAsync(GamePrototypeClasses.game.thinks.Things thing) {
            return base.Channel.SetThingAsync(thing);
        }
        
        public void SetThingToCharacter(GamePrototypeClasses.game.thinks.Things thing, GamePrototypeClasses.game.character.warehouse.CharacterWarehouse warehouse) {
            base.Channel.SetThingToCharacter(thing, warehouse);
        }
        
        public System.Threading.Tasks.Task SetThingToCharacterAsync(GamePrototypeClasses.game.thinks.Things thing, GamePrototypeClasses.game.character.warehouse.CharacterWarehouse warehouse) {
            return base.Channel.SetThingToCharacterAsync(thing, warehouse);
        }
    }
}
