//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePrototypeClient.GamePrototypeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdEntity", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.ValueEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.SpecialThingBonus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.CharacterThings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.CharacterEquipment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.NameEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.UserProfile))]
    public partial class IdEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueEntity", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.SpecialThingBonus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.CharacterThings))]
    public partial class ValueEntity : GamePrototypeClient.GamePrototypeServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialThingBonus", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.game.thinks")]
    [System.SerializableAttribute()]
    public partial class SpecialThingBonus : GamePrototypeClient.GamePrototypeServiceReference.ValueEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.SpecialThingBonusTimeEnum SpecialThingBonusTimeEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.SpecialThinkBonusEnum SpecialThinkBonusTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.SpecialThingBonusTimeEnum SpecialThingBonusTimeEnum {
            get {
                return this.SpecialThingBonusTimeEnumField;
            }
            set {
                if ((this.SpecialThingBonusTimeEnumField.Equals(value) != true)) {
                    this.SpecialThingBonusTimeEnumField = value;
                    this.RaisePropertyChanged("SpecialThingBonusTimeEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.SpecialThinkBonusEnum SpecialThinkBonusType {
            get {
                return this.SpecialThinkBonusTypeField;
            }
            set {
                if ((this.SpecialThinkBonusTypeField.Equals(value) != true)) {
                    this.SpecialThinkBonusTypeField = value;
                    this.RaisePropertyChanged("SpecialThinkBonusType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharacterWarehouse", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.game.character.wareh" +
        "ouse")]
    [System.SerializableAttribute()]
    public partial class CharacterWarehouse : GamePrototypeClient.GamePrototypeServiceReference.ValueEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharacterThings", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.game.character.wareh" +
        "ouse")]
    [System.SerializableAttribute()]
    public partial class CharacterThings : GamePrototypeClient.GamePrototypeServiceReference.ValueEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ThingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid WarehouseIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ThingId {
            get {
                return this.ThingIdField;
            }
            set {
                if ((this.ThingIdField.Equals(value) != true)) {
                    this.ThingIdField = value;
                    this.RaisePropertyChanged("ThingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WarehouseId {
            get {
                return this.WarehouseIdField;
            }
            set {
                if ((this.WarehouseIdField.Equals(value) != true)) {
                    this.WarehouseIdField = value;
                    this.RaisePropertyChanged("WarehouseId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharacterEquipment", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.game.character")]
    [System.SerializableAttribute()]
    public partial class CharacterEquipment : GamePrototypeClient.GamePrototypeServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things ArmorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things BootsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things CloakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things EarringsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things GlovesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things HemletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things NecklaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Potions Potion1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Potions Potion2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Potions Potion3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Potions Potion4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Potions Potion5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things Rings1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things Rings2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things Rings3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Scrolls Scroll1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Scrolls Scroll2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Scrolls Scroll3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things Weapon1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Things Weapon2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Armor {
            get {
                return this.ArmorField;
            }
            set {
                if ((object.ReferenceEquals(this.ArmorField, value) != true)) {
                    this.ArmorField = value;
                    this.RaisePropertyChanged("Armor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Boots {
            get {
                return this.BootsField;
            }
            set {
                if ((object.ReferenceEquals(this.BootsField, value) != true)) {
                    this.BootsField = value;
                    this.RaisePropertyChanged("Boots");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Cloak {
            get {
                return this.CloakField;
            }
            set {
                if ((object.ReferenceEquals(this.CloakField, value) != true)) {
                    this.CloakField = value;
                    this.RaisePropertyChanged("Cloak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Earrings {
            get {
                return this.EarringsField;
            }
            set {
                if ((object.ReferenceEquals(this.EarringsField, value) != true)) {
                    this.EarringsField = value;
                    this.RaisePropertyChanged("Earrings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Gloves {
            get {
                return this.GlovesField;
            }
            set {
                if ((object.ReferenceEquals(this.GlovesField, value) != true)) {
                    this.GlovesField = value;
                    this.RaisePropertyChanged("Gloves");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Hemlet {
            get {
                return this.HemletField;
            }
            set {
                if ((object.ReferenceEquals(this.HemletField, value) != true)) {
                    this.HemletField = value;
                    this.RaisePropertyChanged("Hemlet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Necklace {
            get {
                return this.NecklaceField;
            }
            set {
                if ((object.ReferenceEquals(this.NecklaceField, value) != true)) {
                    this.NecklaceField = value;
                    this.RaisePropertyChanged("Necklace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Potions Potion1 {
            get {
                return this.Potion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Potion1Field, value) != true)) {
                    this.Potion1Field = value;
                    this.RaisePropertyChanged("Potion1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Potions Potion2 {
            get {
                return this.Potion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Potion2Field, value) != true)) {
                    this.Potion2Field = value;
                    this.RaisePropertyChanged("Potion2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Potions Potion3 {
            get {
                return this.Potion3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Potion3Field, value) != true)) {
                    this.Potion3Field = value;
                    this.RaisePropertyChanged("Potion3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Potions Potion4 {
            get {
                return this.Potion4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Potion4Field, value) != true)) {
                    this.Potion4Field = value;
                    this.RaisePropertyChanged("Potion4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Potions Potion5 {
            get {
                return this.Potion5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Potion5Field, value) != true)) {
                    this.Potion5Field = value;
                    this.RaisePropertyChanged("Potion5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Rings1 {
            get {
                return this.Rings1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Rings1Field, value) != true)) {
                    this.Rings1Field = value;
                    this.RaisePropertyChanged("Rings1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Rings2 {
            get {
                return this.Rings2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Rings2Field, value) != true)) {
                    this.Rings2Field = value;
                    this.RaisePropertyChanged("Rings2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Rings3 {
            get {
                return this.Rings3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Rings3Field, value) != true)) {
                    this.Rings3Field = value;
                    this.RaisePropertyChanged("Rings3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Scrolls Scroll1 {
            get {
                return this.Scroll1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Scroll1Field, value) != true)) {
                    this.Scroll1Field = value;
                    this.RaisePropertyChanged("Scroll1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Scrolls Scroll2 {
            get {
                return this.Scroll2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Scroll2Field, value) != true)) {
                    this.Scroll2Field = value;
                    this.RaisePropertyChanged("Scroll2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Scrolls Scroll3 {
            get {
                return this.Scroll3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Scroll3Field, value) != true)) {
                    this.Scroll3Field = value;
                    this.RaisePropertyChanged("Scroll3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Weapon1 {
            get {
                return this.Weapon1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Weapon1Field, value) != true)) {
                    this.Weapon1Field = value;
                    this.RaisePropertyChanged("Weapon1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Things Weapon2 {
            get {
                return this.Weapon2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Weapon2Field, value) != true)) {
                    this.Weapon2Field = value;
                    this.RaisePropertyChanged("Weapon2");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameEntity", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.LevelEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.MainOptionsEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Character))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.ThingEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Potions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Scrolls))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Things))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.UserProfile))]
    public partial class NameEntity : GamePrototypeClient.GamePrototypeServiceReference.IdEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.user")]
    [System.SerializableAttribute()]
    public partial class UserProfile : GamePrototypeClient.GamePrototypeServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.Character UserCharacterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.UserSexEnum UserSexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.Character UserCharacter {
            get {
                return this.UserCharacterField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCharacterField, value) != true)) {
                    this.UserCharacterField = value;
                    this.RaisePropertyChanged("UserCharacter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.UserSexEnum UserSex {
            get {
                return this.UserSexField;
            }
            set {
                if ((this.UserSexField.Equals(value) != true)) {
                    this.UserSexField = value;
                    this.RaisePropertyChanged("UserSex");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevelEntity", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.MainOptionsEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Character))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.ThingEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Potions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Scrolls))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Things))]
    public partial class LevelEntity : GamePrototypeClient.GamePrototypeServiceReference.NameEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainOptionsEntity", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Character))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.ThingEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Potions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Scrolls))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Things))]
    public partial class MainOptionsEntity : GamePrototypeClient.GamePrototypeServiceReference.LevelEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoinsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DefenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HealthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntelligenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MagicAttackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MagicDefenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Agility {
            get {
                return this.AgilityField;
            }
            set {
                if ((this.AgilityField.Equals(value) != true)) {
                    this.AgilityField = value;
                    this.RaisePropertyChanged("Agility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Attack {
            get {
                return this.AttackField;
            }
            set {
                if ((this.AttackField.Equals(value) != true)) {
                    this.AttackField = value;
                    this.RaisePropertyChanged("Attack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Coins {
            get {
                return this.CoinsField;
            }
            set {
                if ((this.CoinsField.Equals(value) != true)) {
                    this.CoinsField = value;
                    this.RaisePropertyChanged("Coins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Defense {
            get {
                return this.DefenseField;
            }
            set {
                if ((this.DefenseField.Equals(value) != true)) {
                    this.DefenseField = value;
                    this.RaisePropertyChanged("Defense");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Health {
            get {
                return this.HealthField;
            }
            set {
                if ((this.HealthField.Equals(value) != true)) {
                    this.HealthField = value;
                    this.RaisePropertyChanged("Health");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Intelligence {
            get {
                return this.IntelligenceField;
            }
            set {
                if ((this.IntelligenceField.Equals(value) != true)) {
                    this.IntelligenceField = value;
                    this.RaisePropertyChanged("Intelligence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MagicAttack {
            get {
                return this.MagicAttackField;
            }
            set {
                if ((this.MagicAttackField.Equals(value) != true)) {
                    this.MagicAttackField = value;
                    this.RaisePropertyChanged("MagicAttack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MagicDefence {
            get {
                return this.MagicDefenceField;
            }
            set {
                if ((this.MagicDefenceField.Equals(value) != true)) {
                    this.MagicDefenceField = value;
                    this.RaisePropertyChanged("MagicDefence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mana {
            get {
                return this.ManaField;
            }
            set {
                if ((this.ManaField.Equals(value) != true)) {
                    this.ManaField = value;
                    this.RaisePropertyChanged("Mana");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Character", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.game.character")]
    [System.SerializableAttribute()]
    public partial class Character : GamePrototypeClient.GamePrototypeServiceReference.MainOptionsEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.CharacterEquipment CharacterEquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.CharacterTypeEnum CharacterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse CharacterWarehouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.CharacterEquipment CharacterEquipment {
            get {
                return this.CharacterEquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.CharacterEquipmentField, value) != true)) {
                    this.CharacterEquipmentField = value;
                    this.RaisePropertyChanged("CharacterEquipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.CharacterTypeEnum CharacterType {
            get {
                return this.CharacterTypeField;
            }
            set {
                if ((this.CharacterTypeField.Equals(value) != true)) {
                    this.CharacterTypeField = value;
                    this.RaisePropertyChanged("CharacterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse CharacterWarehouse {
            get {
                return this.CharacterWarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.CharacterWarehouseField, value) != true)) {
                    this.CharacterWarehouseField = value;
                    this.RaisePropertyChanged("CharacterWarehouse");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThingEntity", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Potions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Scrolls))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GamePrototypeClient.GamePrototypeServiceReference.Things))]
    public partial class ThingEntity : GamePrototypeClient.GamePrototypeServiceReference.MainOptionsEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.SpecialThingBonus SpecialThingBonusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamePrototypeClient.GamePrototypeServiceReference.ThingsTypeEnum ThingsTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.SpecialThingBonus SpecialThingBonus {
            get {
                return this.SpecialThingBonusField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialThingBonusField, value) != true)) {
                    this.SpecialThingBonusField = value;
                    this.RaisePropertyChanged("SpecialThingBonus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamePrototypeClient.GamePrototypeServiceReference.ThingsTypeEnum ThingsType {
            get {
                return this.ThingsTypeField;
            }
            set {
                if ((this.ThingsTypeField.Equals(value) != true)) {
                    this.ThingsTypeField = value;
                    this.RaisePropertyChanged("ThingsType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Potions", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.game.thinks")]
    [System.SerializableAttribute()]
    public partial class Potions : GamePrototypeClient.GamePrototypeServiceReference.ThingEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scrolls", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.game.thinks")]
    [System.SerializableAttribute()]
    public partial class Scrolls : GamePrototypeClient.GamePrototypeServiceReference.ThingEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Things", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.game.thinks")]
    [System.SerializableAttribute()]
    public partial class Things : GamePrototypeClient.GamePrototypeServiceReference.ThingEntity {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSexEnum", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.enums")]
    public enum UserSexEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialThingBonusTimeEnum", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.enums")]
    public enum SpecialThingBonusTimeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Forever = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OneMove = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwoMove = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreeMove = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OneFight = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Time = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecialThinkBonusEnum", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.enums")]
    public enum SpecialThinkBonusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HealthValue = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HealthPercent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArmorValue = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArmorPercent = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AgilityValue = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AgilityPercent = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IntelegenseValue = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IntelegensePercent = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManaValue = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManaPercent = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Freez = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fogot = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bleeding = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Poisoning = 13,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThingsTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.enums")]
    public enum ThingsTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hemlet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Armor = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boots = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gloves = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cloak = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Necklace = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Earrings = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rings = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weapon = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scroll = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Potion = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharacterTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/GamePrototypeClasses.enums")]
    public enum CharacterTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warrior = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assassin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wizard = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GamePrototypeServiceReference.IGamePrototypeService")]
    public interface IGamePrototypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetUserByLogin", ReplyAction="http://tempuri.org/IGamePrototypeService/GetUserByLoginResponse")]
        GamePrototypeClient.GamePrototypeServiceReference.UserProfile GetUserByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetUserByLogin", ReplyAction="http://tempuri.org/IGamePrototypeService/GetUserByLoginResponse")]
        System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.UserProfile> GetUserByLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetUserByEmail", ReplyAction="http://tempuri.org/IGamePrototypeService/GetUserByEmailResponse")]
        GamePrototypeClient.GamePrototypeServiceReference.UserProfile GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetUserByEmail", ReplyAction="http://tempuri.org/IGamePrototypeService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.UserProfile> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/IsUserLoginDataValid", ReplyAction="http://tempuri.org/IGamePrototypeService/IsUserLoginDataValidResponse")]
        bool IsUserLoginDataValid(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/IsUserLoginDataValid", ReplyAction="http://tempuri.org/IGamePrototypeService/IsUserLoginDataValidResponse")]
        System.Threading.Tasks.Task<bool> IsUserLoginDataValidAsync(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetAllThings", ReplyAction="http://tempuri.org/IGamePrototypeService/GetAllThingsResponse")]
        GamePrototypeClient.GamePrototypeServiceReference.Things[] GetAllThings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetAllThings", ReplyAction="http://tempuri.org/IGamePrototypeService/GetAllThingsResponse")]
        System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.Things[]> GetAllThingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetAllCharacterThings", ReplyAction="http://tempuri.org/IGamePrototypeService/GetAllCharacterThingsResponse")]
        GamePrototypeClient.GamePrototypeServiceReference.CharacterThings[] GetAllCharacterThings(GamePrototypeClient.GamePrototypeServiceReference.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetAllCharacterThings", ReplyAction="http://tempuri.org/IGamePrototypeService/GetAllCharacterThingsResponse")]
        System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.CharacterThings[]> GetAllCharacterThingsAsync(GamePrototypeClient.GamePrototypeServiceReference.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetThingById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetThingByIdResponse")]
        GamePrototypeClient.GamePrototypeServiceReference.Things GetThingById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetThingById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetThingByIdResponse")]
        System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.Things> GetThingByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetCharacterById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetCharacterByIdResponse")]
        GamePrototypeClient.GamePrototypeServiceReference.Character GetCharacterById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetCharacterById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetCharacterByIdResponse")]
        System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.Character> GetCharacterByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetWarehouseById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetWarehouseByIdResponse")]
        GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse GetWarehouseById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetWarehouseById", ReplyAction="http://tempuri.org/IGamePrototypeService/GetWarehouseByIdResponse")]
        System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse> GetWarehouseByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetWarehouse", ReplyAction="http://tempuri.org/IGamePrototypeService/GetWarehouseResponse")]
        GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse GetWarehouse(GamePrototypeClient.GamePrototypeServiceReference.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/GetWarehouse", ReplyAction="http://tempuri.org/IGamePrototypeService/GetWarehouseResponse")]
        System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse> GetWarehouseAsync(GamePrototypeClient.GamePrototypeServiceReference.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetUserProfile", ReplyAction="http://tempuri.org/IGamePrototypeService/SetUserProfileResponse")]
        void SetUserProfile(GamePrototypeClient.GamePrototypeServiceReference.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetUserProfile", ReplyAction="http://tempuri.org/IGamePrototypeService/SetUserProfileResponse")]
        System.Threading.Tasks.Task SetUserProfileAsync(GamePrototypeClient.GamePrototypeServiceReference.UserProfile userProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/SetCharacterResponse")]
        void SetCharacter(GamePrototypeClient.GamePrototypeServiceReference.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/SetCharacterResponse")]
        System.Threading.Tasks.Task SetCharacterAsync(GamePrototypeClient.GamePrototypeServiceReference.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/UpdateCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/UpdateCharacterResponse")]
        void UpdateCharacter(GamePrototypeClient.GamePrototypeServiceReference.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/UpdateCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/UpdateCharacterResponse")]
        System.Threading.Tasks.Task UpdateCharacterAsync(GamePrototypeClient.GamePrototypeServiceReference.Character character);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetThing", ReplyAction="http://tempuri.org/IGamePrototypeService/SetThingResponse")]
        void SetThing(GamePrototypeClient.GamePrototypeServiceReference.Things thing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetThing", ReplyAction="http://tempuri.org/IGamePrototypeService/SetThingResponse")]
        System.Threading.Tasks.Task SetThingAsync(GamePrototypeClient.GamePrototypeServiceReference.Things thing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetThingToCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/SetThingToCharacterResponse")]
        void SetThingToCharacter(GamePrototypeClient.GamePrototypeServiceReference.Things thing, GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse warehouse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamePrototypeService/SetThingToCharacter", ReplyAction="http://tempuri.org/IGamePrototypeService/SetThingToCharacterResponse")]
        System.Threading.Tasks.Task SetThingToCharacterAsync(GamePrototypeClient.GamePrototypeServiceReference.Things thing, GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse warehouse);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGamePrototypeServiceChannel : GamePrototypeClient.GamePrototypeServiceReference.IGamePrototypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GamePrototypeServiceClient : System.ServiceModel.ClientBase<GamePrototypeClient.GamePrototypeServiceReference.IGamePrototypeService>, GamePrototypeClient.GamePrototypeServiceReference.IGamePrototypeService {
        
        public GamePrototypeServiceClient() {
        }
        
        public GamePrototypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GamePrototypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamePrototypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamePrototypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GamePrototypeClient.GamePrototypeServiceReference.UserProfile GetUserByLogin(string login) {
            return base.Channel.GetUserByLogin(login);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.UserProfile> GetUserByLoginAsync(string login) {
            return base.Channel.GetUserByLoginAsync(login);
        }
        
        public GamePrototypeClient.GamePrototypeServiceReference.UserProfile GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.UserProfile> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public bool IsUserLoginDataValid(string login, string pass) {
            return base.Channel.IsUserLoginDataValid(login, pass);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserLoginDataValidAsync(string login, string pass) {
            return base.Channel.IsUserLoginDataValidAsync(login, pass);
        }
        
        public GamePrototypeClient.GamePrototypeServiceReference.Things[] GetAllThings() {
            return base.Channel.GetAllThings();
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.Things[]> GetAllThingsAsync() {
            return base.Channel.GetAllThingsAsync();
        }
        
        public GamePrototypeClient.GamePrototypeServiceReference.CharacterThings[] GetAllCharacterThings(GamePrototypeClient.GamePrototypeServiceReference.Character character) {
            return base.Channel.GetAllCharacterThings(character);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.CharacterThings[]> GetAllCharacterThingsAsync(GamePrototypeClient.GamePrototypeServiceReference.Character character) {
            return base.Channel.GetAllCharacterThingsAsync(character);
        }
        
        public GamePrototypeClient.GamePrototypeServiceReference.Things GetThingById(System.Guid id) {
            return base.Channel.GetThingById(id);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.Things> GetThingByIdAsync(System.Guid id) {
            return base.Channel.GetThingByIdAsync(id);
        }
        
        public GamePrototypeClient.GamePrototypeServiceReference.Character GetCharacterById(System.Guid id) {
            return base.Channel.GetCharacterById(id);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.Character> GetCharacterByIdAsync(System.Guid id) {
            return base.Channel.GetCharacterByIdAsync(id);
        }
        
        public GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse GetWarehouseById(System.Guid id) {
            return base.Channel.GetWarehouseById(id);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse> GetWarehouseByIdAsync(System.Guid id) {
            return base.Channel.GetWarehouseByIdAsync(id);
        }
        
        public GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse GetWarehouse(GamePrototypeClient.GamePrototypeServiceReference.Character character) {
            return base.Channel.GetWarehouse(character);
        }
        
        public System.Threading.Tasks.Task<GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse> GetWarehouseAsync(GamePrototypeClient.GamePrototypeServiceReference.Character character) {
            return base.Channel.GetWarehouseAsync(character);
        }
        
        public void SetUserProfile(GamePrototypeClient.GamePrototypeServiceReference.UserProfile userProfile) {
            base.Channel.SetUserProfile(userProfile);
        }
        
        public System.Threading.Tasks.Task SetUserProfileAsync(GamePrototypeClient.GamePrototypeServiceReference.UserProfile userProfile) {
            return base.Channel.SetUserProfileAsync(userProfile);
        }
        
        public void SetCharacter(GamePrototypeClient.GamePrototypeServiceReference.Character character) {
            base.Channel.SetCharacter(character);
        }
        
        public System.Threading.Tasks.Task SetCharacterAsync(GamePrototypeClient.GamePrototypeServiceReference.Character character) {
            return base.Channel.SetCharacterAsync(character);
        }
        
        public void UpdateCharacter(GamePrototypeClient.GamePrototypeServiceReference.Character character) {
            base.Channel.UpdateCharacter(character);
        }
        
        public System.Threading.Tasks.Task UpdateCharacterAsync(GamePrototypeClient.GamePrototypeServiceReference.Character character) {
            return base.Channel.UpdateCharacterAsync(character);
        }
        
        public void SetThing(GamePrototypeClient.GamePrototypeServiceReference.Things thing) {
            base.Channel.SetThing(thing);
        }
        
        public System.Threading.Tasks.Task SetThingAsync(GamePrototypeClient.GamePrototypeServiceReference.Things thing) {
            return base.Channel.SetThingAsync(thing);
        }
        
        public void SetThingToCharacter(GamePrototypeClient.GamePrototypeServiceReference.Things thing, GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse warehouse) {
            base.Channel.SetThingToCharacter(thing, warehouse);
        }
        
        public System.Threading.Tasks.Task SetThingToCharacterAsync(GamePrototypeClient.GamePrototypeServiceReference.Things thing, GamePrototypeClient.GamePrototypeServiceReference.CharacterWarehouse warehouse) {
            return base.Channel.SetThingToCharacterAsync(thing, warehouse);
        }
    }
}
